### ISSUE TITLE
GF QA

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/Signika#2]
- Zcaron, zcaron appear to have no outlines
- Bold AE renders badly in DW (probably our ttfautohint)
- Some pixel jumps in DW
- Line-height in FireFox are bad (strip out MVAR table. This is a known issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1492477)

![glyphs_modified](https://user-images.githubusercontent.com/7525512/50977348-fe6cf600-14e9-11e9-9c7d-6146b7c75c49.gif)

I think I may play with the ttfautohint-vf settings to see if I can find a better fit. Thank you for using it as well.

[signika-vf-qa.zip](https://github.com/thundernixon/Signika/files/2745982/signika-vf-qa.zip)

**Comment by m4rc1e** [comment]
Best ttfautohint-vf results I've managed so far is by using the following:

```
ttfautohint-vf --stem-width-mode nnn Signika-VF.ttf Signika-VF2.ttf
```

Reg:
![desktop_windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/50982683-a1773d00-14f5-11e9-889b-69301107a333.gif)

**Comment by m4rc1e** [comment]
These ttfautohint settings also solve the AE glyph issue.

**Comment by thundernixon** [comment]
Thanks for filing this as an issue! It makes it very clear what to do next.
